### ISSUE TITLE
bc0a.com domain is wrongly categorized and moved to the blacklist

### ISSUE THREAD

**Issue by RajKonyala** [mypdns/Support#2]
We (Brightedge) have discovered that one of our domains, **bc0a.com**, has been incorrectly categorized and moved to the blacklist. This domain does not contain any scripts related to adware or tracking. We use a separate domain, b0e8.com, for tracking. It appears that bc0a.com was blacklisted at the same time as b0e8.com. We would like to know what exactly triggered the decision to consider bc0a.com as containing adware or tracking information. This domain is important to us.

https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json

https://github.com/mypdns/matrix/issues/481

Thank you!

**Comment by spirillen** [comment]
Thanks for reaching out to us, Let me try to help you out here:

As you can read in the commit msg, then the decision or reason for adding the domain is based on https://github.com/disconnectme/disconnect-tracking-protection/blob/master/descriptions.md#brightedge

-------------


> BrightEdge 
> Spirillen on 6/11/2024, 8:46:25 PM
> Closes https://github.com/mypdns/matrix/issues/481
> Fixes https://github.com/mypdns/matrix/issues/482
> 
> Ref: https://github.com/disconnectme/disconnect-tracking-protection/blob/master/descriptions.md#brightedge

----------------

When you are looking at https://github.com/mypdns/matrix/issues/481, you'll see that there have been found a fingerprinting2 script on the domain.

and as proofed here, it is still active

```bash
url -I https://cdn.b0e8.com/conv_v3.js
HTTP/2 200 
date: Thu, 25 Jul 2024 22:10:57 GMT
cache-control: public, max-age=3600
expires: Thu, 25 Jul 2024 23:10:57 GMT
last-modified: Mon, 13 Mar 2023 18:19:37 GMT
```

One could argument for blacklisting the hole domain rather than only the CDN. but with no access to the domain from the public web. This is standard security/privacy measures.

![image](https://github.com/user-attachments/assets/facd81c4-3518-4a4e-b61d-635ce1aa1f4b)

If you like to get `bc0a.com` of the list, you need to delete any fingerprinter and other track-ware from the domain

Hoping this could be to your help

issue for `b0e8.com`: https://github.com/mypdns/matrix/issues/565

**Comment by RajKonyala** [comment]
Thank you so much for the details. I apologize for bothering you again. I believe you are referring to two domains here: **b0e8.com** and **bc0a.com**. We are working on the process to remove the fingerprint scripts from **b0e8.com** domain. Additionally, there are no fingerprint/track-ware scripts in the bc0a.com domain. Do you have any references indicating that **bc0a.com** has these scripts, if not Can we safely remove **bc0a.com** from the blacklist.

**Comment by spirillen** [comment]
Hi @RajKonyala it seems the `bc0a.com` and `b0e8.com` likes to switch places here, messing it all up.

**A**: `bc0A.com` I have not been able to currently locate any unwanted software, will be removed. Could I ask you to make a removal request i https://github.com/mypdns/matrix/issues/481 for continuity of the domain records?

**E**: `b0E8.com` Is still hosting fingerprinting software, so this one will stay, for now, according to your commend. Once you've cleaned this domain, please make removal request to https://github.com/mypdns/matrix/issues/565

---------------

Now I do have a question to you regarding `brightedge.com`(https://github.com/mypdns/matrix/issues/482) and `valuemyweb.com` (https://github.com/mypdns/matrix/issues/758), will these domains keep hosting/collecting track- spyware as demonstrated by https://github.com/disconnectme/disconnect-tracking-protection/blob/master/descriptions.md#technical-review-22 ? and in which subdomains will you be using for tracking. 

If you can't or wont response to this question, both will be blacklisted by wildcard for safeguarding privacy first.

**Comment by RajKonyala** [comment]
Thank you for your response.

I will make a removal request on mypdns/matrix#481 as you suggested for continuity of the domain **bc0a.com**.

Regarding brightedge.com (mypdns/matrix#482) and valuemyweb.com (mypdns/matrix#758), we are using the fingerprint software to track visitors on our own website. Could you please provide more details on how this could be a problem so that we can take appropriate action?

**Comment by spirillen** [comment]
> Could you please provide more details on how this could be a problem so that we can take appropriate action?

This is very simple a privacy concern., and all tracking should always be on a opt-in basis.

> we can take appropriate action?

You would remember that the matrix project is first and foremost a knowledge base for why any records are blacklisted https://github.com/mypdns#my-privacy-dns

Secondly, this makes it a very suitable and reliable source for building blacklist from the matrix of data in https://github.com/mypdns/matrix/tree/master/source as every single records have been verified by humans before their added. This also means the lists are very binary (true|false) as you also experienced with bc0a, its cleared once the script is deleted and the domain in "clean".

This also means we do not remove any active records from the database, and users of our data are to keep their own whitelists, https://github.com/mypdns/matrix?tab=readme-ov-file#why-not-whitelisting. The concept is you are free to write about your trackers in the issues for those domain, giving other a good solid insight in what is being collected and why, this leaves the true powers to the users, to determine how to handle your domains... or reinvent something old... make tracking an OPT-in options for users...

**Comment by RajKonyala** [comment]
Thank you for the details. We will work on the process for Brightedge.com and ValueMyWeb.com.

I submitted a request to remove **bc0a.com** from the tracking protection list, but it has not been removed yet, and the domain is still blocked in the Firefox browser. How can this be resolved?

Here is the link to the tracking protection list:
https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json#L3779

You can submit your request here:
https://disconnect.me/trackerprotection#submissions_and_appeals

**Comment by spirillen** [comment]
Hi @RajKonyala I do not have any power at @disconnetme and as I can read from their responses, you'll have to change your AUP + Privacy Policy before they will reconsider your request for changes.

From my little search tool, I can see you are still marked at easyprivacy...

## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

```css
```

#### Sorted result

```css
```

### Search result from easylist

```css
easyprivacy/easyprivacy_thirdparty.txt:||bc0a.com/api/
easyprivacy/easyprivacy_thirdparty.txt:||bc0a.com/autopilot/
easyprivacy/easyprivacy_thirdparty.txt:||bc0a.com/be_ixf_js_sdk.js
easyprivacy/easyprivacy_thirdparty.txt:||bc0a.com/marvel.js
```

## Search in [Matrix](https://www.mypdns.org/)


Search results from [Matrix](https://www.mypdns.org) blacklist project

```css
```


Did not find any matching RPZ records


+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
\+ Thanks to [My Privacy DNS](https://www.mypdns.org/) for this knowledge
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by spirillen** [comment]
Apparently moved to https://github.com/mypdns/Support/issues/5
